### ISSUE TITLE
Add support for Metamask login

### ISSUE THREAD

**Issue by joaosantos15** [ConsenSys/mythxjs#15]
Currently on the dashboard, login is done by having the user sign a Metamask message, instead of providing username and password.

To support this, Mythxjs should:

- Make a `/auth/challenge` to the mythx API
- Construct the Metamask challenge and have Metamask prompt the user
- Get the signature from Metamask
- Send that signature to the `auth/login` endpoint on the mythx api

**Comment by joaosantos15** [comment]
cc @Gtonizuka

**Comment by Gtonizuka** [comment]
There is a PR waiting to be merged in for this
